# Homework 4

## sklearn 的 StandardScaler

In [1]:
from sklearn.preprocessing import StandardScaler

In [2]:
data = [[-1, 2], [-0.5, 6], [0, 10], [1, 18]]

In [3]:
scaler = StandardScaler()

In [4]:
scaler.fit(data)

StandardScaler(copy=True, with_mean=True, with_std=True)

In [5]:
scaler.mean_

array([-0.125,  9.   ])

In [7]:
scaler.var_

array([ 0.546875, 35.      ])

In [6]:
scaler.transform(data)

array([[-1.18321596, -1.18321596],
       [-0.50709255, -0.50709255],
       [ 0.16903085,  0.16903085],
       [ 1.52127766,  1.52127766]])

In [8]:
scaler.transform([[2,2]])

array([[ 2.87352447, -1.18321596]])

## MyStandardScaler

In [9]:
import numpy as np

In [27]:
class MyStandardScaler:
    def __init__(self):
        self.mean = None
        self.var = None #初始化定義
        
    def fit(self, data):
        self.mean = np.mean(data, axis = 0)
        self.var = np.var(data, axis = 0)
            
    def transform(self, data):
        return (np.array(data) - self.mean ) / (self.var**0.5)
    
    def fit_transform(self, data):
        self.fit(data)
        return self.transform(data)    
            

### 驗證

In [28]:
MyScaler = MyStandardScaler()

In [29]:
MyScaler.fit(data)

In [30]:
MyScaler.mean

array([-0.125,  9.   ])

In [31]:
MyScaler.var

array([ 0.546875, 35.      ])

In [32]:
MyScaler.transform(data)

array([[-1.18321596, -1.18321596],
       [-0.50709255, -0.50709255],
       [ 0.16903085,  0.16903085],
       [ 1.52127766,  1.52127766]])

In [34]:
MyScaler.transform([2,2])

array([ 2.87352447, -1.18321596])